In [2]:
import pandas as pd
import numpy as np

In [2]:
def check_prime(n):
    if n<=1:
        print(" is not a prime number")
        
    else:
        for i in range(2,int(n/2)+1):
            if n%i==0:
                print("is not a prime number")
                break
            else:
                print("is a prime number")
                break
            
check_prime(6)

is not a prime number


In [3]:
def area_of_rectangle(length, width):
    area = length * width
    return area
print("Area of rectangle is", area_of_rectangle(5, 10))

Area of rectangle is 50


In [4]:
def maximum_of_three(a,b,c):
    if a>=b:
        if a>c:
            print(f"{a} is the largest number")
            
        else:
            print(f"{c} is the largest number")
            
    else:
        if b>c:
            print(f"{b} is the largest number")
            
        else:
            print(f"{c} is the largest number")
            
maximum_of_three(500,485,50)

500 is the largest number


In [5]:
def reverse_string(string):
    reversed_string= string[::-1]
    return reversed_string

print(reverse_string("Hello World!"))

!dlroW olleH


In [6]:
def count_vowel(str):
    count=0
    for char in str:
        if char in "aeiouAEIOU" :
            count+=1
            
    print(count)
            
count_vowel("I am A disCO DancEr")

7


In [7]:
def check_pallindrome(str):
    rev_str=str[::-1]
    if str==rev_str:
        print(f"String {str} is pallindrome")
        
    else:
        print(f"String {str} is not pallindrome")
    
check_pallindrome("eee madam eee")

String eee madam eee is pallindrome


In [8]:
name="john"
def function():
    name= "sumit"
    print(name)
    
function()
print(name)

sumit
john


In [9]:
x=99
def func(y):
    z=x+y
    return z
func(1)

100

In [10]:
class Bike:
    def __init__(self,brand,model):
        self.brand=brand
        self.model=model
    
myBike= Bike("Honda","Cbz")
print(myBike.brand)
print(myBike.model)

Honda
Cbz


In [11]:
class Car:
    def __init__(self,brand,model):
        self.brand=brand
        self.model=model
        
    def fullname(self):
        print("Full name of car is ",self.brand,"",self.model)
        
myCar= Car("Hyundai", "Creta")
myCar.fullname()

class ElectricCar(Car):
    def __init__(self,size,brand,model):
        super().__init__(brand,model)
        self.size=size
mynew=ElectricCar(4,"a","b")
print(mynew.brand)
print(mynew.size)
  

Full name of car is  Hyundai  Creta
a
4


In [23]:
class ElectricCar(Car):
    def __init__(self, brand, model, size):
        super().__init__(brand, model)
        self.size = size

In [13]:
class Car:
    def __init__(self,brand,top_speed,colour):
        self.__brand=brand
        self.top_speed=top_speed
        self.colour=colour
        
    def get_brand(self):
        return self.__brand
    def set_brand(self,new_brand):
        self.__brand=new_brand
    def get_data(self):
        print(self.__brand)
        print(self.top_speed)
        print(self.colour)
    
       
    
        
myCar= Car("Hyundai",150,"Red")
# print(myCar.brand)
# myCar.get_data()
print(myCar.get_brand())
myCar.set_brand("Tata")
print(myCar.get_brand())

Hyundai
Tata


In [14]:
class Vehicle:
    def start_engine(self):
        pass
    
class Car(Vehicle):
    total_cars = 0
    def __init__(self,brand,model,year):
        Car.total_cars += 1
        self.brand = brand
        self.__model = model
        self.year = year
        self.is_running = False
        
    def get_model(self):
        return self.__model
    
    def set_model(self, new_model):
        self.__model = new_model
        
    def start_engine(self):
        self.is_running = True
        print(f"{self.__model} engine started.")
        
    def get_data(self):
        print(self.brand)
        print(self.__model)
        print(self.year)
        
class ElectricCar(Car):
    # def __init__(self, brand, __model, year, battery_size):
    #     super().__init__(brand, __model, year)
    #     self.battery_size = battery_size
        
    def start_engine(self):
        self.is_running = True
        print(f"{self.get_model()} electric engine started.")
        
myCar = Car("toyota","Supra",2020)
myCar.get_data()
myCar.start_engine()
newCar = ElectricCar("Tesla", "Model S", 2021)
newCar.get_data()
newCar.start_engine()  
print("Total cars created:", Car.total_cars)     

toyota
Supra
2020
Supra engine started.
Tesla
Model S
2021
Model S electric engine started.
Total cars created: 2


In [15]:
import numpy as np

In [16]:
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [17]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [18]:
lst=[1,2,3]
print(lst*2)
print(arr_1d*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [19]:
arr1=np.zeros(3)
print(arr1)
arr2=np.ones((3,5))
print(arr2)
arr3=np.eye(5)
print(arr3)

[0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
lin=np.linspace(0,200,6)
print(lin)
rng=np.arange(0,21,3)
print(rng)
arr4=np.full((2,3),10)
print(arr4)
rnd=np.random.rand(5,5)*100
print(rnd)
rndint=np.random.randint(11,size=(5,5))
print(rndint)

print(rng.tolist())
print(rng.astype(dtype=float))
print(np.info(np.eye))
print(rng.size)
print(rng.shape)
print(rng.dtype)

[  0.  40.  80. 120. 160. 200.]
[ 0  3  6  9 12 15 18]
[[10 10 10]
 [10 10 10]]
[[55.02871596 39.71090271 14.9813025   2.06906383 22.46693338]
 [ 4.59155562 26.40936091 39.14599716 29.56637635 24.65512683]
 [64.09956174 13.65316115 46.60144507 44.31622584 95.01983145]
 [80.43955897  6.34963234 94.26186736 88.28431464 42.89435121]
 [84.20714626 37.13482218 77.41758311 45.13191751 56.17529514]]
[[7 6 5 9 6]
 [8 5 2 3 5]
 [0 8 2 6 8]
 [0 7 0 4 6]
 [1 9 1 3 8]]
[0, 3, 6, 9, 12, 15, 18]
[ 0.  3.  6.  9. 12. 15. 18.]
 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype :

In [21]:
arr6=np.array([10,20,30,50,40])
np.copy(arr6)
print(arr6.view(dtype=float))
arr6.sort()
print(arr6)

arr7=np.array([[10,30,20],[55,40,89]])
arr7.sort(axis=1)
print(arr7)

# print(arr7.flatten())

# print(arr7.T)
# print(arr7)

# arr7.reshape(2,3)
arr7.resize(6,5)
print(arr7)

[4.94e-323 9.88e-323 1.48e-322 2.47e-322 1.98e-322]
[10 20 30 40 50]
[[10 20 30]
 [40 55 89]]
[[10 20 30 40 55]
 [89  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [28]:
import numpy as np
arr7=np.array([10,20,30,40,50])
arr7=np.append(arr7,100)
print(arr7)

# arr7=np.insert(arr7,2,25)
print(arr7)

arr8=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr8)

arr8=np.delete(arr8,2,axis=1)
print(arr8)


arr9=np.array([[10,20,30,40,50],[60,70,80,90,100]])
# print(arr9[0,1])

# arr9[0,1]=40
# print(arr9[0,1])

# arr9[:1]

# arr7=np.split(arr7,2)
# print(arr7)
np.hsplit(arr9,1)
print(arr9)

arr10=np.array([1,2,3,4,5,6,7,8,9])
arr11=np.array([10,20,30,40,50,60,70,80,90])
# np.add(arr10,arr11)
# np.subtract(arr10,arr11)
# np.multiply(arr10,arr11)
# np.divide(arr10,arr11)
# np.power(arr10,10)
# np.sqrt(arr10)
# np.sin(arr10)
# np.log(arr10)
# np.abs(arr10)
# np.ceil(arr10)
# np.round(arr10)
# np.mean(arr10)
# arr10.sum()
# arr10.min()
# arr10.max()
# np.var(arr10)
# np.std(arr10)
# np.corrcoef(arr10)
arr12=(np.random.seed(42))
print(arr12)



[ 10  20  30  40  50 100]
[ 10  20  30  40  50 100]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
None


In [40]:
arr=np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
# arr.shape
# arr.size
# arr.dtype
# arr.ndim
# arr.itemsize
print(arr.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]]


In [49]:
arr=np.array([[1,4], [2,5], [3,6]])
arr2=np.array([1,2])
print(arr+arr2)



print(4+5*2)
print(type(7.5))
print((type("Hello")))
print(list("abc"))

[[2 6]
 [3 7]
 [4 8]]
14
<class 'float'>
<class 'str'>
['a', 'b', 'c']


In [66]:
# s1=pd.Series([1,2,3,4,5])
# s1

arr=np.array([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
s1=pd.Series(arr)
s2
s1.pow(s2)


0                      1
1                1048576
2        205891132094649
3                      0
4   -6776596920136667815
dtype: int64

In [11]:
age=pd.Series(np.array([20,25,30,35,40]),
    np.arange(0,10,2))
age

0    20
2    25
4    30
6    35
8    40
dtype: int64

In [ ]:
mark = pd.Series([20, 21, 22, 23, 24], index=['a', 'b', 'c', 'd', 'e']) 
print(mark)



a    20
b    21
c    22
d    23
e    24
dtype: int64


In [12]:
expense_dict={'rent':2500,'grocery':3000,'travelling':2000,'insurance':5000}
expense_series=pd.Series(expense_dict)
expense_series

rent          2500
grocery       3000
travelling    2000
insurance     5000
dtype: int64

In [62]:
classes_dict={
    "A":["Maths","Science","English"],
    "B":["Maths","Physics"],
    "C":"Chemistry"
}

classes_series=pd.Series(classes_dict)
classes_series

# classes_series.index
# classes_series.values

print("\n",classes_series[['A','B']])


 A    [Maths, Science, English]
B             [Maths, Physics]
dtype: object


In [54]:
std_data= np.array(['Ram','Sita','Laxmi','Krishna'])
std_series=pd.Series(std_data)
std_series
std_series[:-3]

0    Ram
dtype: object

In [63]:
student_series=pd.Series(
    np.array([457,456,540,348,502,480]),
    index=['Ram','Sita','Laxmi','Krishna','Madhab','Arjun']
)

student_series[student_series>500]

Laxmi     540
Madhab    502
dtype: int64

In [67]:
sales=pd.Series([200,590,400,550])
sales*2

0     400
1    1180
2     800
3    1100
dtype: int64

In [72]:
scores=pd.Series([88,50,75,90,20],
                 index=['a','b','c','d','e'])
studentrank=scores.rank()
studentrank

a    4.0
b    2.0
c    3.0
d    5.0
e    1.0
dtype: float64

In [75]:
salesdata=pd.Series([250,np.nan,140,np.nan,560],
                    index=['jan','feb','mar','apr','may'])
sorted_salesdata=salesdata.sort_values(ascending=False, na_position='last')
sorted_salesdata

may    560.0
jan    250.0
mar    140.0
feb      NaN
apr      NaN
dtype: float64

In [4]:
salesdata=pd.Series(
    [250,np.nan,175,300,np.nan,220],
    index=[7,4,3,2,8,9]
)

salesdata.isnull()

7    False
4     True
3    False
2    False
8     True
9    False
dtype: bool

In [13]:
week1_sales=np.linspace(start=0,stop=300,num=5)
week2_sales=np.linspace(start=0,stop=400,num=5)

week1_sales_series=pd.Series(data=week1_sales)
week2_sales_series=pd.Series(data=week2_sales)

# week1_sales_series
# week2_sales_series

pd.concat([week1_sales_series,week2_sales_series])
# week1_sales_series.append(week2_sales_series) # this is removed and updated


0      0.0
1     75.0
2    150.0
3    225.0
4    300.0
0      0.0
1    100.0
2    200.0
3    300.0
4    400.0
dtype: float64

In [16]:
ml=['Python','Numpy','Pandas','Matplotlib','ML Algorithms','Statistics']
df=pd.DataFrame(ml)
df

0
0         Python
1          Numpy
2         Pandas
3     Matplotlib
4  ML Algorithms
5     Statistics

In [ ]:
# Dataframe from list of list

courses_list=[['ML Foundation',8000],['IOT',5000],['Web Developement',6500]]
df=pd.DataFrame(courses_list,columns=['Course','Fee'])
df

Course   Fee
0     ML Foundation  8000
1               IOT  5000
2  Web Developement  6500

In [18]:
# Dataframe from a dictionary

data={
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,35,60],
    'City':['New York','London','Chicago']
}
df=pd.DataFrame(data)
df

Name  Age      City
0    Alice   25  New York
1      Bob   35    London
2  Charlie   60   Chicago

In [ ]:
# Dataframe with index from a dictionary

data={
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,35,60],
    'City':['New York','London','Chicago']
}
df=pd.DataFrame(data,index=['A1','A2','A3'])
df.columns=["Namee","Agee","Cityy"] # Custom column
df

type(df)
df[['Namee','Agee']] #accesing multiple columns of the dataframe

df["Agee"].max()
df['Agee'].mean()
df.index
df.columns
df.set_index("Agee",inplace=True)
df.columns

Index(['Namee', 'Agee', 'Cityy'], dtype='object')

In [21]:
# Dataframe from a list of dictionaries

sales_data=[
    {'Date':'2025-06-01', 'Product':'Laptop', 'Units_sold':5, 'Revenue':50000},
    {'Date':'2025-06-01', 'Product':'Mouse', 'Units_sold':25, 'Revenue':2500},
    {'Date':'2025-06-02', 'Product':'Keyboard', 'Units_sold':15, 'Revenue':7500},
    {'Date':'2025-06-02', 'Product':'Monitor', 'Units_sold':7, 'Revenue':21000}
]
df=pd.DataFrame(sales_data)
df

Date   Product  Units_sold  Revenue
0  2025-06-01    Laptop           5    50000
1  2025-06-01     Mouse          25     2500
2  2025-06-02  Keyboard          15     7500
3  2025-06-02   Monitor           7    21000

In [31]:
# Reading from excel

df=pd.read_excel('excel_for_pandas.xlsx',sheet_name='Sheet1') # Load the excel file
df.index=['First','Second','Third','Forth','Fifth','Sixth','Seventh','Eighth']#cusom index
df
df

Name  Age         City  Pincode
First       Tony   23          USA     5453
Second      Thor   25       Asgard     4323
Third    Natasha   19          USA     4236
Forth      Bruce   30          USA     4565
Fifth     Tchala   28      Wakanda     7897
Sixth     Naruto   26  Hidden Leaf     6775
Seventh     Goku   18  Mount Paozu     2767
Eighth   Saitama   22        Japan     3456

In [24]:
# Reading from csv

df=pd.read_csv('Obesity_Classification.csv') # Load the csv file
df

ID  Age  Gender  Height  Weight   BMI          Label
0      1   25    Male     175      80  25.3  Normal Weight
1      2   30  Female     160      60  22.5  Normal Weight
2      3   35    Male     180      90  27.3     Overweight
3      4   40  Female     150      50  20.0    Underweight
4      5   45    Male     190     100  31.2          Obese
..   ...  ...     ...     ...     ...   ...            ...
103  106   11    Male     175      10   3.9    Underweight
104  107   16  Female     160      10   3.9    Underweight
105  108   21    Male     180      15   5.6    Underweight
106  109   26  Female     150      15   5.6    Underweight
107  110   31    Male     190      20   8.3    Underweight

[108 rows x 7 columns]

In [43]:
# Reading from json

df=pd.read_json('iris.json') # Load the json file
df
df.tail()
df.describe()

sepalLength  sepalWidth  petalLength  petalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.057333     3.758000    1.199333
std       0.828066    0.435866     1.765298    0.762238
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000