In [2]:
def check_prime(n):
    if n<=1:
        print(" is not a prime number")
        
    else:
        for i in range(2,int(n/2)+1):
            if n%i==0:
                print("is not a prime number")
                break
            else:
                print("is a prime number")
                break
            
check_prime(6)

is not a prime number


In [3]:
def area_of_rectangle(length, width):
    area = length * width
    return area
print("Area of rectangle is", area_of_rectangle(5, 10))

Area of rectangle is 50


In [4]:
def maximum_of_three(a,b,c):
    if a>=b:
        if a>c:
            print(f"{a} is the largest number")
            
        else:
            print(f"{c} is the largest number")
            
    else:
        if b>c:
            print(f"{b} is the largest number")
            
        else:
            print(f"{c} is the largest number")
            
maximum_of_three(500,485,50)

500 is the largest number


In [5]:
def reverse_string(string):
    reversed_string= string[::-1]
    return reversed_string

print(reverse_string("Hello World!"))

!dlroW olleH


In [6]:
def count_vowel(str):
    count=0
    for char in str:
        if char in "aeiouAEIOU" :
            count+=1
            
    print(count)
            
count_vowel("I am A disCO DancEr")

7


In [7]:
def check_pallindrome(str):
    rev_str=str[::-1]
    if str==rev_str:
        print(f"String {str} is pallindrome")
        
    else:
        print(f"String {str} is not pallindrome")
    
check_pallindrome("eee madam eee")

String eee madam eee is pallindrome


In [8]:
name="john"
def function():
    name= "sumit"
    print(name)
    
function()
print(name)

sumit
john


In [9]:
x=99
def func(y):
    z=x+y
    return z
func(1)

100

In [10]:
class Bike:
    def __init__(self,brand,model):
        self.brand=brand
        self.model=model
    
myBike= Bike("Honda","Cbz")
print(myBike.brand)
print(myBike.model)

Honda
Cbz


In [11]:
class Car:
    def __init__(self,brand,model):
        self.brand=brand
        self.model=model
        
    def fullname(self):
        print("Full name of car is ",self.brand,"",self.model)
        
myCar= Car("Hyundai", "Creta")
myCar.fullname()

class ElectricCar(Car):
    def __init__(self,size,brand,model):
        super().__init__(brand,model)
        self.size=size
mynew=ElectricCar(4,"a","b")
print(mynew.brand)
print(mynew.size)
  

Full name of car is  Hyundai  Creta
a
4


In [23]:
class ElectricCar(Car):
    def __init__(self, brand, model, size):
        super().__init__(brand, model)
        self.size = size

In [13]:
class Car:
    def __init__(self,brand,top_speed,colour):
        self.__brand=brand
        self.top_speed=top_speed
        self.colour=colour
        
    def get_brand(self):
        return self.__brand
    def set_brand(self,new_brand):
        self.__brand=new_brand
    def get_data(self):
        print(self.__brand)
        print(self.top_speed)
        print(self.colour)
    
       
    
        
myCar= Car("Hyundai",150,"Red")
# print(myCar.brand)
# myCar.get_data()
print(myCar.get_brand())
myCar.set_brand("Tata")
print(myCar.get_brand())

Hyundai
Tata


In [14]:
class Vehicle:
    def start_engine(self):
        pass
    
class Car(Vehicle):
    total_cars = 0
    def __init__(self,brand,model,year):
        Car.total_cars += 1
        self.brand = brand
        self.__model = model
        self.year = year
        self.is_running = False
        
    def get_model(self):
        return self.__model
    
    def set_model(self, new_model):
        self.__model = new_model
        
    def start_engine(self):
        self.is_running = True
        print(f"{self.__model} engine started.")
        
    def get_data(self):
        print(self.brand)
        print(self.__model)
        print(self.year)
        
class ElectricCar(Car):
    # def __init__(self, brand, __model, year, battery_size):
    #     super().__init__(brand, __model, year)
    #     self.battery_size = battery_size
        
    def start_engine(self):
        self.is_running = True
        print(f"{self.get_model()} electric engine started.")
        
myCar = Car("toyota","Supra",2020)
myCar.get_data()
myCar.start_engine()
newCar = ElectricCar("Tesla", "Model S", 2021)
newCar.get_data()
newCar.start_engine()  
print("Total cars created:", Car.total_cars)     

toyota
Supra
2020
Supra engine started.
Tesla
Model S
2021
Model S electric engine started.
Total cars created: 2


In [15]:
import numpy as np

In [16]:
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [17]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [18]:
lst=[1,2,3]
print(lst*2)
print(arr_1d*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [19]:
arr1=np.zeros(3)
print(arr1)
arr2=np.ones((3,5))
print(arr2)
arr3=np.eye(5)
print(arr3)

[0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
lin=np.linspace(0,200,6)
print(lin)
rng=np.arange(0,21,3)
print(rng)
arr4=np.full((2,3),10)
print(arr4)
rnd=np.random.rand(5,5)*100
print(rnd)
rndint=np.random.randint(11,size=(5,5))
print(rndint)

print(rng.tolist())
print(rng.astype(dtype=float))
print(np.info(np.eye))
print(rng.size)
print(rng.shape)
print(rng.dtype)

[  0.  40.  80. 120. 160. 200.]
[ 0  3  6  9 12 15 18]
[[10 10 10]
 [10 10 10]]
[[55.02871596 39.71090271 14.9813025   2.06906383 22.46693338]
 [ 4.59155562 26.40936091 39.14599716 29.56637635 24.65512683]
 [64.09956174 13.65316115 46.60144507 44.31622584 95.01983145]
 [80.43955897  6.34963234 94.26186736 88.28431464 42.89435121]
 [84.20714626 37.13482218 77.41758311 45.13191751 56.17529514]]
[[7 6 5 9 6]
 [8 5 2 3 5]
 [0 8 2 6 8]
 [0 7 0 4 6]
 [1 9 1 3 8]]
[0, 3, 6, 9, 12, 15, 18]
[ 0.  3.  6.  9. 12. 15. 18.]
 eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None,
     like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype :

In [21]:
arr6=np.array([10,20,30,50,40])
np.copy(arr6)
print(arr6.view(dtype=float))
arr6.sort()
print(arr6)

arr7=np.array([[10,30,20],[55,40,89]])
arr7.sort(axis=1)
print(arr7)

# print(arr7.flatten())

# print(arr7.T)
# print(arr7)

# arr7.reshape(2,3)
arr7.resize(6,5)
print(arr7)

[4.94e-323 9.88e-323 1.48e-322 2.47e-322 1.98e-322]
[10 20 30 40 50]
[[10 20 30]
 [40 55 89]]
[[10 20 30 40 55]
 [89  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [28]:
import numpy as np
arr7=np.array([10,20,30,40,50])
arr7=np.append(arr7,100)
print(arr7)

# arr7=np.insert(arr7,2,25)
print(arr7)

arr8=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr8)

arr8=np.delete(arr8,2,axis=1)
print(arr8)


arr9=np.array([[10,20,30,40,50],[60,70,80,90,100]])
# print(arr9[0,1])

# arr9[0,1]=40
# print(arr9[0,1])

# arr9[:1]

# arr7=np.split(arr7,2)
# print(arr7)
np.hsplit(arr9,1)
print(arr9)

arr10=np.array([1,2,3,4,5,6,7,8,9])
arr11=np.array([10,20,30,40,50,60,70,80,90])
# np.add(arr10,arr11)
# np.subtract(arr10,arr11)
# np.multiply(arr10,arr11)
# np.divide(arr10,arr11)
# np.power(arr10,10)
# np.sqrt(arr10)
# np.sin(arr10)
# np.log(arr10)
# np.abs(arr10)
# np.ceil(arr10)
# np.round(arr10)
# np.mean(arr10)
# arr10.sum()
# arr10.min()
# arr10.max()
# np.var(arr10)
# np.std(arr10)
# np.corrcoef(arr10)
arr12=(np.random.seed(42))
print(arr12)



[ 10  20  30  40  50 100]
[ 10  20  30  40  50 100]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
None


In [40]:
arr=np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
# arr.shape
# arr.size
# arr.dtype
# arr.ndim
# arr.itemsize
print(arr.astype(float))

[[1. 2. 3.]
 [4. 5. 6.]]


In [49]:
arr=np.array([[1,4], [2,5], [3,6]])
arr2=np.array([1,2])
print(arr+arr2)



print(4+5*2)
print(type(7.5))
print((type("Hello")))
print(list("abc"))

[[2 6]
 [3 7]
 [4 8]]
14
<class 'float'>
<class 'str'>
['a', 'b', 'c']
