NumPy

In [9]:
import numpy as np

1.Create a 1D array from a list.


In [5]:
lst=[1,2,3,4,5]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

2. Create a 3x3 array of zeros.


In [8]:
arr=np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Create a 2x2 array of ones.

In [9]:
arr=np.ones([2,2])
arr

array([[1., 1.],
       [1., 1.]])

4. Generate array from 0 to 10 (exclusive).

In [11]:
arr=np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5. Create 5 evenly spaced numbers between 0 and 1.


In [14]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 4x4 identity matrix.

In [16]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. Reshape 1D array to 2D.

In [28]:
arr=np.array([1,2,3,4])
arr2=arr.reshape(2,2)
arr2

array([[1, 2],
       [3, 4]])

8. Get the shape and dtype of an array.

In [42]:
arr=np.array([[5,6,7,8]])
np.shape(arr)
print(arr.shape)
print(arr.dtype)
print(arr.size)

(1, 4)
int64
4


9. Reverse a NumPy array.

In [60]:
arr=np.array([5,6,7,8])
print(arr[::-1])

[8 7 6 5]


10. Extract even numbers from an array.

In [10]:
arr=np.array([5,6,7,8])
even=arr[arr%2==0]
even

array([6, 8])

11. Find the max in each row.

In [70]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr
arr.max(axis=1)

array([4, 8])

12. Compute the mean, std, and median of an array.


In [72]:
arr=np.array([5,6,7,8])
print(f"mean: {arr.mean()}")
print(f"std: {arr.std()}")
print(f"median: {np.median(arr)}")

mean: 6.5
std: 1.118033988749895
median: 6.5


13. Stack two arrays vertically.

In [73]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[10,20,30,40],[50,60,70,80]])
np.concat((arr,arr2),axis=0)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

14. Stack two arrays horizontally.

In [74]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[10,20,30,40],[50,60,70,80]])
np.concat((arr,arr2),axis=1)

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

15. Stack two arrays horizontally.


In [75]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[10,20,30,40],[50,60,70,80]])
np.concat((arr,arr2),axis=1)

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

16. Find the unique values and their counts.

In [82]:
arr=np.array([[1,2,3,4,7,5],[5,6,7,8,2,1]])
unique, counts = np.unique(arr, return_counts=True)
unique_counts = dict(zip(unique, counts))  
print(unique_counts) 


{np.int64(1): np.int64(2), np.int64(2): np.int64(2), np.int64(3): np.int64(1), np.int64(4): np.int64(1), np.int64(5): np.int64(2), np.int64(6): np.int64(1), np.int64(7): np.int64(2), np.int64(8): np.int64(1)}


17. Replace NaN with column means.


In [ ]:
arr = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
print(arr)
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
arr


[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

18. Get index of min and max values.


In [ ]:
arr = np.array([7, 8, 9, 1, 2, 3])
print(arr)
print(arr[arr.argmax()])
print(arr[arr.argmin()])



[7 8 9 1 2 3]
9
1


19. Create a 3D array of random integers.

In [ ]:
arr = np.random.randint(0, 10, (2, 3, 4))
print(arr)

[[[6 3 9 4]
  [5 8 5 1]
  [3 5 6 9]]

 [[9 1 6 7]
  [6 7 7 1]
  [9 6 5 3]]]


20. Use np.where() to replace values


In [26]:
arr=np.array([[1,2,3,4,5,60,70,8]])
arr2=np.where(arr > 10,5,arr)
print(arr2)


[[1 2 3 4 5 5 5 8]]


Pandas

In [2]:
import pandas as pd

1. Create a Series using a Python list.


In [ ]:
lst=[1,2,3,4,5]
series=pd.Series(lst)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Create a Series with custom string indices.




In [ ]:
lst=[1,2,3,4,5]
series=pd.Series(lst,index=[1,2,3,4,5])
series

1    1
2    2
3    3
4    4
5    5
dtype: int64

3. Create a Series from a dictionary.


In [7]:
lst={
    1:'a',
    2:'b',
    3:'c',
    4:'d',
    5:'e'}
series=pd.Series(lst)
series

1    a
2    b
3    c
4    d
5    e
dtype: object

4. Access first 3 elements of a Series.


In [8]:
ser=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
ser.head(3)

a    1
b    2
c    3
dtype: int64

5. Filter Series elements greater than 50.



In [29]:
series=pd.Series([1,2,3,4,5,6,8,52,45,95,82])
lst=series[series>50]
print(lst)

7     52
9     95
10    82
dtype: int64


6. Add two Series with different indices.



In [4]:
lst=[1,2,3,4,5]
df=pd.Series(lst,index=[1,2,3,4,5])
lst2=[10,20,30,40,50]
df2=pd.Series(lst2,index=['a','b','c',1,2])
df3=df+df2
df3

1    41.0
2    52.0
3     NaN
4     NaN
5     NaN
a     NaN
b     NaN
c     NaN
dtype: float64


7. Multiply a Series by a scalar.


In [5]:
lst=[1,2,3,4,5]
df=pd.Series(lst,index=[1,2,3,4,5])
print(df*2)

1     2
2     4
3     6
4     8
5    10
dtype: int64


8. Use .multiply() method to multiply with scalar.


In [7]:
lst=[1,2,3,4,5]
df=pd.Series(lst,index=[1,2,3,4,5])
np.multiply(df,2)


1     2
2     4
3     6
4     8
5    10
dtype: int64

10. Sort Series by values descending.


In [ ]:
series = pd.Series([5, 2, 9, 1, 5, 6])
sorted_series = series.sort_values(ascending=False)
sorted_series


2    9
5    6
4    5
0    5
1    2
3    1
dtype: int64

11. Sort Series by index.


In [35]:
series = pd.Series([5, 2, 9, 1, 5, 6])
sorted_series = series.sort_index(ascending=False)
sorted_series

5    6
4    5
3    1
2    9
1    2
0    5
dtype: int64

12. Check for null values.



In [ ]:
series = pd.Series([1, 2, None, 4, None])
print(series.isnull())

0    False
1    False
2     True
3    False
4     True
dtype: bool


14. Concatenate two Series using concat().


In [37]:
ser1= pd.Series([1, 2, 3, 4, 5])
ser2= pd.Series([5, 4, 3, 2, 1])
print(pd.concat([ser1,ser2]))

0    1
1    2
2    3
3    4
4    5
0    5
1    4
2    3
3    2
4    1
dtype: int64


15. Concatenate two Series using append().


In [41]:
# append is no longer a part of pandas.
# We have to use concat instead.

16. Retrieve first 5 elements using .head()



In [ ]:
series=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i'])
series.head(5)

a    1
b    2
c    3
d    4
e    5
dtype: int64

17. Retrieve last 5 elements using .tail()


In [4]:
series=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i'])
series.tail(5)

e    5
f    6
g    7
h    8
i    9
dtype: int64

18. Convert Series to DataFrame.


In [6]:
series=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i'])
df=pd.DataFrame(series)
df

0
a  1
b  2
c  3
d  4
e  5
f  6
g  7
h  8
i  9

19. Replace NaN with 0.


In [44]:
series=pd.Series([1,np.nan,3,4,np.nan,6,np.nan,8,9],index=['a','b','c','d','e','f','g','h','i'])
print(series)
series.replace(np.nan, 0, inplace=True)
print(series)

a    1.0
b    NaN
c    3.0
d    4.0
e    NaN
f    6.0
g    NaN
h    8.0
i    9.0
dtype: float64
a    1.0
b    0.0
c    3.0
d    4.0
e    0.0
f    6.0
g    0.0
h    8.0
i    9.0
dtype: float64


20. Drop missing values.


In [45]:
series=pd.Series([1,np.nan,3,4,np.nan,6,np.nan,8,9],index=['a','b','c','d','e','f','g','h','i'])
print(series)
filtered=series.dropna()
filtered

a    1.0
b    NaN
c    3.0
d    4.0
e    NaN
f    6.0
g    NaN
h    8.0
i    9.0
dtype: float64


a    1.0
c    3.0
d    4.0
f    6.0
h    8.0
i    9.0
dtype: float64

21. Check Series data type.



In [31]:
series=pd.Series([1,2,3,4,5,6,7,8,9],index=['a','b','c','d','e','f','g','h','i'])
series.dtype

dtype('int64')